language: python
python:
- 3.6

cache: pip

before_script:
- pip install pycodestyle
- pip install .
script:
- pycodestyle puzh tests setup.py
- python -m unittest

before_deploy:
- export VERSION=$(python -c "import puzh;print(puzh.__version__)")
- export PYPI_VERSION=$(curl -s https://pypi.org/pypi/puzh/json | jq -r .info.version)
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    condition: $(printf "$VERSION\n$PYPI_VERSION" | sort -V | head -n 1) != $VERSION
    branch: master
